"""add sender in conversation

Revision ID: 24e500cbf4c6
Revises: e137461c241a
Create Date: 2025-05-05 22:50:16.126863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24e500cbf4c6"
down_revision: Union[str, None] = "e137461c241a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation", sa.Column("sender", sa.String(), nullable=True))
    op.create_unique_constraint(None, "feedback", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feedback", type_="unique")
    op.drop_column("conversation", "sender")
    # ### end Alembic commands ###
