"""add new column in file

Revision ID: 56300a90e0e9
Revises: 3e7b650bfb04
Create Date: 2025-02-23 21:35:56.566048

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56300a90e0e9"
down_revision: Union[str, None] = "3e7b650bfb04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "conversation", ["id"])
    op.add_column("file", sa.Column("meta", sa.JSON(), nullable=False))
    op.add_column("file", sa.Column("data", sa.JSON(), nullable=False))
    op.create_unique_constraint(None, "file", ["id"])
    op.create_unique_constraint(None, "knowledge", ["id"])
    op.create_unique_constraint(None, "message", ["id"])
    op.create_unique_constraint(None, "tool", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "tool", type_="unique")
    op.drop_constraint(None, "message", type_="unique")
    op.drop_constraint(None, "knowledge", type_="unique")
    op.drop_constraint(None, "file", type_="unique")
    op.drop_column("file", "data")
    op.drop_column("file", "meta")
    op.drop_constraint(None, "conversation", type_="unique")
    # ### end Alembic commands ###
