"""remove unique for phone number

Revision ID: 869d67468458
Revises: f2842abdd73d
Create Date: 2025-05-31 01:31:58.779738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "869d67468458"
down_revision: Union[str, None] = "f2842abdd73d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_phone_number_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_phone_number_key", "user", ["phone_number"])
    # ### end Alembic commands ###
