"""add seminar in opportunity

Revision ID: 9a8e92302d33
Revises: 21e39ac0a317
Create Date: 2025-05-15 05:28:39.476472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a8e92302d33"
down_revision: Union[str, None] = "21e39ac0a317"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE opportunitytype ADD VALUE 'SEMINAR';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
