"""add count in collection

Revision ID: b042ad4875b4
Revises: cc8ad1c4e696
Create Date: 2025-05-23 23:03:07.013147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b042ad4875b4"
down_revision: Union[str, None] = "cc8ad1c4e696"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection", sa.Column("count", sa.Integer(), nullable=True, default=0)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "count")
    # ### end Alembic commands ###
