"""fix user

Revision ID: f2842abdd73d
Revises: b042ad4875b4
Create Date: 2025-05-31 01:26:34.305733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f2842abdd73d"
down_revision: Union[str, None] = "b042ad4875b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "nrp")
    op.drop_column("user", "nip")
    op.drop_column("user", "profile_picture")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("profile_picture", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user", sa.Column("nip", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user", sa.Column("nrp", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
